### ISSUE TITLE
2.0无法引用 3.0$mailer->html提示要求3个参数

### ISSUE THREAD

**Issue by echoconfig** [yzh52521/think-mail#7]
这个还能不能用现在

**Comment by yuanzhihai** [comment]
你单独 修改一下 

public function html($content, array $param = [], array $config = []) 
看看可以么

**Comment by echoconfig** [comment]
这个在哪里 是3.0的方法吗  我用的时候报错Too few arguments to function mailer\\Mailer::text(), 1 passed in xxxxx on line 48 and exactly 3 expected

**Comment by yuanzhihai** [comment]
public function text($content, array $param = [], array $config = []) 

这个方法也改一下 试试

**Comment by echoconfig** [comment]
The \"\" mailer DSN must contain a scheme.

**Comment by echoconfig** [comment]
return [
        'scheme'          => 'smtp',
        'host'            => '', // 服务器地址
        'username'        => '',
        'password'        => '', // 密码
        'port'            => 465, // SMTP服务器端口号,一般为25
        'options'         => [],
        'dsn'             => '',
        'debug'           => false, // 开启debug模式会直接抛出异常, 记录邮件发送日志
        'embed'           => 'embed:', // 邮件中嵌入图片元数据标记
];  

这个写得也不完整啊

**Comment by echoconfig** [comment]
这个怎么解决呢

**Comment by yuanzhihai** [comment]
> return [ 'scheme' => 'smtp', 'host' => '', // 服务器地址 'username' => '', 'password' => '', // 密码 'port' => 465, // SMTP服务器端口号,一般为25 'options' => [], 'dsn' => '', 'debug' => false, // 开启debug模式会直接抛出异常, 记录邮件发送日志 'embed' => 'embed:', // 邮件中嵌入图片元数据标记 ];
> 
> 这个写得也不完整啊

注释调 dsn

**Comment by echoconfig** [comment]
The body must be a string, a resource or null (got \"int\").

**Comment by echoconfig** [comment]
$code = mt_rand(100000, 999999);
$mailer = Mailer::instance();

            $mailer->from(input('email'))
                ->to(input('email'))
                ->subject('操作验证')
                ->html($code)
                ->send();

**Comment by yuanzhihai** [comment]
刚才测试了 2.0 没有问题 
2.0 和 3.0 配置不一样
用的扩展的也不一样
